version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: azure-tenant-grapher-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Set initial password (change this!)
      - NEO4J_AUTH=neo4j/azure-grapher-2024
      # Enable APOC procedures (useful for graph algorithms)
      - NEO4J_PLUGINS=["apoc"]
      # Performance tuning
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # Security settings
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p azure-grapher-2024 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
