version: "3.8"
services:
  neo4j:
    image: neo4j:5.19
    container_name: ${NEO4J_CONTAINER_NAME:-azure-tenant-grapher-neo4j}
    restart: unless-stopped
    ports:

      - "${NEO4J_PORT}:7687"
      - "8747:7474"
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
    volumes:
      - type: volume
        source: ${NEO4J_DATA_VOLUME:-azure-tenant-grapher-neo4j-data}
        target: /data
      - ./neo4j-logs:/logs
      - ./neo4j-import:/var/lib/neo4j/import
      - ./neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474/browser/"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  azure-tenant-grapher-neo4j-data:
