"""Tests for Terraform import blocks generation (Issue #412)."""

import pytest

from src.iac.emitters.terraform_emitter import TerraformEmitter
from src.iac.traverser import TenantGraph


class TestImportBlocksGeneration:
    """Test suite for import blocks generation feature."""

    def test_import_blocks_disabled_by_default(self, tmp_path):
        """Test that import blocks are not generated by default."""
        emitter = TerraformEmitter()
        assert emitter.auto_import_existing is False
        assert emitter.import_strategy == "resource_groups"

    def test_import_blocks_enabled_with_flag(self, tmp_path):
        """Test that import blocks are generated when flag is enabled."""
        emitter = TerraformEmitter(
            auto_import_existing=True, import_strategy="resource_groups"
        )
        assert emitter.auto_import_existing is True
        assert emitter.import_strategy == "resource_groups"

    def test_import_blocks_list_format(self, tmp_path):
        """Test that import blocks use correct list format for Terraform 1.5+."""
        # Create mock graph with resource groups
        graph = TenantGraph(
            resources=[
                {
                    "type": "Microsoft.Compute/resourceGroups",
                    "name": "rg1",
                    "location": "eastus",
                    "id": "/subscriptions/sub1/resourceGroups/rg1",
                },
                {
                    "type": "Microsoft.Compute/resourceGroups",
                    "name": "rg2",
                    "location": "westus",
                    "id": "/subscriptions/sub1/resourceGroups/rg2",
                },
            ]
        )

        emitter = TerraformEmitter(
            auto_import_existing=True,
            import_strategy="resource_groups",
            target_subscription_id="sub1",
        )

        # Generate mock terraform config
        terraform_config = {
            "resource": {
                "azurerm_resource_group": {
                    "rg1": {"name": "rg1", "location": "eastus"},
                    "rg2": {"name": "rg2", "location": "westus"},
                }
            }
        }

        # Generate import blocks
        import_blocks = emitter._generate_import_blocks(
            terraform_config, graph.resources
        )

        # Verify format
        assert isinstance(import_blocks, list), "Import blocks must be a list"
        assert len(import_blocks) == 2
        assert all("to" in block and "id" in block for block in import_blocks)
        assert import_blocks[0]["to"] == "azurerm_resource_group.rg1"
        assert "/subscriptions/sub1/resourceGroups/rg1" in import_blocks[0]["id"]

    def test_import_strategy_resource_groups(self, tmp_path):
        """Test resource_groups import strategy."""
        terraform_config = {
            "resource": {
                "azurerm_resource_group": {
                    "test_rg": {"name": "test-rg", "location": "eastus"}
                }
            }
        }

        emitter = TerraformEmitter(
            auto_import_existing=True,
            import_strategy="resource_groups",
            target_subscription_id="test-sub",
        )

        import_blocks = emitter._generate_import_blocks(terraform_config, [])

        assert len(import_blocks) == 1
        assert import_blocks[0]["to"] == "azurerm_resource_group.test_rg"
        assert "test-rg" in import_blocks[0]["id"]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])

    def test_import_strategy_all_resources_placeholder(self):
        """Test that all_resources strategy is acknowledged but not fully implemented."""
        terraform_config = {
            "resource": {
                "azurerm_resource_group": {
                    "rg1": {"name": "rg1", "location": "eastus"}
                },
                "azurerm_storage_account": {
                    "storage1": {"name": "storage1", "location": "eastus"}
                },
            }
        }

        emitter = TerraformEmitter(
            auto_import_existing=True,
            import_strategy="all_resources",
            target_subscription_id="test-sub",
        )

        import_blocks = emitter._generate_import_blocks(terraform_config, [])

        # Currently returns empty for all_resources (needs full implementation)
        # This test documents current behavior
        assert isinstance(import_blocks, list)
        # TODO: When all_resources is implemented, this should return > 1 block

    def test_import_blocks_with_cross_tenant(self):
        """Test import blocks use correct subscription ID for cross-tenant."""
        terraform_config = {
            "resource": {
                "azurerm_resource_group": {
                    "test_rg": {"name": "test-rg", "location": "eastus"}
                }
            }
        }

        # Cross-tenant scenario
        emitter = TerraformEmitter(
            auto_import_existing=True,
            import_strategy="resource_groups",
            source_subscription_id="source-sub-123",
            target_subscription_id="target-sub-456",
        )

        import_blocks = emitter._generate_import_blocks(terraform_config, [])

        # Should use target subscription
        assert len(import_blocks) == 1
        assert "target-sub-456" in import_blocks[0]["id"]
        assert "source-sub-123" not in import_blocks[0]["id"]

    def test_import_blocks_metrics_integration(self):
        """Test that import blocks are tracked in metrics."""
        emitter = TerraformEmitter(
            auto_import_existing=True,
            import_strategy="resource_groups",
            target_subscription_id="test-sub"
        )

        # Initially should be 0
        assert emitter.get_import_blocks_count() == 0

        # After generation should be > 0
        terraform_config = {
            "resource": {
                "azurerm_resource_group": {
                    "test_rg": {"name": "test-rg", "location": "eastus"}
                }
            }
        }
        
        import_blocks = emitter._generate_import_blocks(terraform_config, [])
        
        # This doesn't set the counter (that happens in emit())
        # but we can verify the method works
        assert len(import_blocks) == 1
