"""Tenant creation command.

This module provides the 'create-tenant' command for creating
tenant graphs from markdown specifications.

Issue #482: CLI Modularization
"""

import asyncio
import sys

import click

from src.utils.neo4j_startup import ensure_neo4j_running


def create_tenant_from_markdown(text: str):
    """Create a tenant from markdown using TenantCreator."""
    from src.llm_descriptions import create_llm_generator
    from src.tenant_creator import TenantCreator

    llm_generator = create_llm_generator()
    creator = TenantCreator(llm_generator=llm_generator)

    # Store stats for return
    creation_stats = None

    async def _run():
        from src.exceptions import LLMGenerationError

        nonlocal creation_stats

        try:
            spec = await creator.create_from_markdown(text)
            # Check if spec was generated by LLM for permissive validation
            is_llm_generated = getattr(spec, "_is_llm_generated", False)
            creation_stats = await creator.ingest_to_graph(
                spec, is_llm_generated=is_llm_generated
            )
        except LLMGenerationError as e:
            click.echo("LLM output parsing failed during tenant creation.", err=True)
            click.echo(f"Error: {e}", err=True)
            click.echo(
                "Action: The LLM response could not be parsed. Check your Azure OpenAI configuration and try again.\n"
                "If the error persists, run with --log-level DEBUG and review the prompt and raw LLM response below.",
                err=True,
            )
            if hasattr(e, "context") and e.context:
                prompt = e.context.get("prompt")
                raw_response = e.context.get("raw_response")
                if prompt:
                    click.echo("Prompt used for LLM:", err=True)
                    click.echo(prompt, err=True)
                if raw_response:
                    click.echo("Raw LLM response:", err=True)
                    click.echo(raw_response, err=True)
            sys.exit(1)

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        # If we're already in an event loop, schedule the task and wait for it
        task = loop.create_task(_run())
        # For CLI, block until done
        import nest_asyncio

        nest_asyncio.apply()
        loop.run_until_complete(task)
    else:
        asyncio.run(_run())

    return creation_stats


@click.command("create-tenant")
@click.argument("markdown_file", type=click.Path(exists=True))
def create_tenant(markdown_file: str):
    """Create a tenant graph from a tenant spec."""
    try:
        ensure_neo4j_running()
        with open(markdown_file, encoding="utf-8") as f:
            text = f.read()
        print("DEBUG: Raw markdown file contents:\n", text)

        # Get creation statistics
        stats = create_tenant_from_markdown(text)

        # Display success with detailed feedback
        click.echo("")
        click.echo("Tenant successfully created in Neo4j!")
        click.echo("")

        # Display resource counts
        if stats:
            click.echo("Resources created:")
            click.echo("-" * 40)

            # Display non-zero counts in a logical order
            display_order = [
                ("tenant", "Tenant"),
                ("subscriptions", "Subscriptions"),
                ("resource_groups", "Resource Groups"),
                ("resources", "Resources"),
                ("users", "Users"),
                ("groups", "Groups"),
                ("service_principals", "Service Principals"),
                ("managed_identities", "Managed Identities"),
                ("admin_units", "Admin Units"),
                ("rbac_assignments", "RBAC Assignments"),
                ("relationships", "Relationships"),
            ]

            for key, label in display_order:
                if key in stats and stats[key] > 0:
                    click.echo(f"  {label}: {stats[key]}")

            click.echo("-" * 40)
            click.echo(f"  Total entities: {stats.get('total', 0)}")
            click.echo("")
            click.echo("Next steps:")
            click.echo("  Run 'atg visualize' to see the graph")
            click.echo("  Run 'atg build' to enrich with more data")
        else:
            click.echo("No statistics available")

    except Exception as e:
        click.echo(
            f"Failed to create tenant: {e}\n"
            "Action: Check that the markdown file is valid and that Neo4j and Azure OpenAI are configured correctly. Run with --log-level DEBUG for more details.",
            err=True,
        )
        sys.exit(1)


# For backward compatibility
create_tenant_command = create_tenant

__all__ = ["create_tenant", "create_tenant_command", "create_tenant_from_markdown"]
