# Development Environment Configuration
# Tags: v*-dev (e.g., v1.0.0-dev)

name: dev
description: Development environment for ATG Remote Service

# No protection rules - allow immediate deployment
protection_rules: []

deployment_branch_policy:
  custom_branch_policies: false

# Required secrets (must be configured in GitHub)
secrets:
  - NEO4J_URI              # bolt://your-neo4j-dev.com:7687
  - NEO4J_PASSWORD         # Neo4j database password
  - API_KEY                # API authentication key
  - TARGET_TENANT_ID       # Azure tenant ID for scanning
  - AZURE_CREDENTIALS      # Service principal credentials (JSON)
  - AZURE_SUBSCRIPTION_ID  # Azure subscription ID
