name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NEO4J_PASSWORD: ci-neo4j-pass # pragma: allowlist secret
    services:
      neo4j:
        image: neo4j:5
        env:
          NEO4J_AUTH: neo4j/ci-neo4j-pass
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
        ports:
          - 7687:7687
        options: >-
          --health-cmd "cypher-shell -u neo4j -p ci-neo4j-pass 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Python dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run migrations
        env:
          NEO4J_URI: bolt://localhost:7687
          NEO4J_USER: neo4j
          PYTHONPATH: .
        run: |
          . .venv/bin/activate
          .venv/bin/python scripts/run_migrations.py

      - name: Run tests
        env:
          PYTHONPATH: .
        run: .venv/bin/python -m pytest -q
